[package]
name = "cask"
version = "0.1.27"
authors = ["Axetroy <axetroy.dev@gmail.com>"]
readme = "README.md"
keywords = ["cask", "distributed", "binary", "package", "manager"]
repository = "https://github.com/axetroy/cask.rs"
description = """
General distributed binary distribution package management, written in Rust.
"""

edition = "2021"

[[bin]]
name = "cask"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.1.2"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
eyre = "0.6.7"
toml = "0.5.0"
reqwest = { version = "0.11.9", default-features = false, features = ["stream", "rustls-tls"] }
futures = "0.3.21"
indicatif = "0.16.2"
futures-util = "0.3.21"
tokio = { version = "1", features = ["full"] }
chrono = "0.4.19"
tar = "0.4.38"
tinytemplate = "1.1"
dirs = "4.0.0"
sha2 = "0.10.2"
libflate = "1"
url = "2.2.2"
zip = "0.5.13"
which = "4.2.4"
semver = "1.0.6"
wait-timeout = "0.1.5"
thiserror = "1.0.30"
tabled = "0.5.0"

[profile.release]
# https://github.com/johnthagen/min-sized-rust
strip = true  # Automatically strip symbols from the binary.
opt-level = "z"  # Optimize for size.
lto = true
codegen-units = 1
panic = "abort"