[package]
name = "cask"
version = "0.1.0"
authors = ["Axetroy <axetroy.dev@gmail.com>"]
readme = "README.md"
keywords = ["cask", "git", "project", "manager"]
repository = "https://github.com/axetroy/cask.rs"
description = """
A command line tool, manage your hundreds of repository, written with Rust.
"""

edition = "2021"

[[bin]]
name = "cask"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.1.2"
ctrlc = { version = "3.2.1", features = ["termination"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
eyre = "0.6.7"
toml = "0.5.0"
serde_derive = "1.0.136"
reqwest = { version = "0.11.9", features = ["blocking", "json", "stream"] }
futures = "0.3.21"
async-recursion = "1.0.0"
indicatif = "0.16.2"
futures-util = "0.3.21"
tokio = { version = "1", features = ["full"] }
chrono = "0.4.19"
zip = "0.5"
flate2 = "1.0.22"
tar = "0.4.38"
tinytemplate = "1.1"
dirs = "4.0.0"
sha2 = "0.10.2"