[package]
name = "gpm"
bin = "gpm"
version = "0.1.12"
authors = ["Axetroy <axetroy.dev@gmail.com>"]
keywords = ["gpm", "git", "project", "manager"]
repository = "https://github.com/axetroy/gpm.rs"
description = """
A command line tool, manage your hundreds of repository, written with Rust.
"""

[target]
darwin_amd64 = { url = "https://github.com/axetroy/gpm.rs/releases/download/v0.1.12/gpm_darwin_amd64.tar.gz" }
darwin_arm64 = { url = "https://github.com/axetroy/gpm.rs/releases/download/v0.1.12/gpm_darwin_arm64.tar.gz" }
windows_386 = { url = "https://github.com/axetroy/gpm.rs/releases/download/v0.1.12/gpm_darwin_arm64.tar.gz" }
