[target.x86_64-unknown-freebsd]
image = "ghcr.io/cross-rs/x86_64-unknown-freebsd:edge"

[target.aarch64-unknown-freebsd]
image = "svenstaro/cross-aarch64-unknown-freebsd:latest"

[build.env]
passthrough = [
    "CARGO_INCREMENTAL",
    "RUST_BACKTRACE",
    "CARGO_TERM_COLOR",
]