[target.x86_64-unknown-freebsd]
image = "rustembedded/cross:x86_64-unknown-freebsd"

[target.x86_64-pc-windows-gnu]
image = "rustembedded/cross:x86_64-pc-windows-gnu"

[build.env]
passthrough = [
    "CARGO_INCREMENTAL",
    "RUST_BACKTRACE",
    "CARGO_TERM_COLOR",
]