[package]
name = "extractor"
version = "0.1.0"
edition = "2021"

[lib]
path = "lib.rs"

[dependencies]
eyre = "0.6.8"
libflate = "2.1.0"
tar = "0.4.38"
zip = "1.3.0"
bzip2-rs = "0.1.2"
thiserror = "1.0.61"
regex = "1.5.5"
serde = { version = "1.0.136", features = ["derive"] }
