name: build

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc

          - os: windows-latest
            target: aarch64-pc-windows-msvc

          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl

          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl

          - os: macos-11
            target: x86_64-apple-darwin

          - os: macos-11
            target: aarch64-apple-darwin

    env:
      CARGO_INCREMENTAL: 0
      RUST_BACKTRACE: full
      CARGO_TERM_COLOR: always

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: "1.59.0"

      - name: Log versions
        run: |
          rustc --version
          cargo --version
      - name: Configure cargo data directory
        run: |
          echo "CARGO_HOME=$(pwd)/.cargo_home" >> $GITHUB_ENV
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |-
            .cargo_home
            target/*/.*
            target/*/build
            target/*/deps
          key: ${{ matrix.config.os }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ matrix.config.os }}-

      - name: Build (linux) - x86_64-unknown-linux-musl
        if: startsWith(matrix.os, 'ubuntu') && startsWith(matrix.target, 'x86_64-unknown-linux-musl')
        run: |
          sudo apt-get install -y musl-tools

          wget --quiet https://musl.cc/x86_64-linux-musl-cross.tgz

          tar -xvzf x86_64-linux-musl-cross.tgz

          export PATH=$PATH:$(pwd)/x86_64-linux-musl-cross/bin

          rustup target add ${{ matrix.target }}

          cargo build --release --locked --target ${{ matrix.target }}

          tar -cvzf target/${{ matrix.target }}/release/cask_${{ matrix.target }}.tar.gz --directory=target/${{ matrix.target }}/release cask

      - name: Build (linux) - aarch64-unknown-linux-musl
        if: startsWith(matrix.os, 'ubuntu') && startsWith(matrix.target, 'aarch64-unknown-linux-musl')
        run: |
          wget --quiet https://musl.cc/aarch64-linux-musl-cross.tgz

          tar -xvzf aarch64-linux-musl-cross.tgz

          export PATH=$PATH:$(pwd)/aarch64-linux-musl-cross/bin

          rustup target add ${{ matrix.target }}

          cargo build --release --locked --target ${{ matrix.target }}

          tar -cvzf target/${{ matrix.target }}/release/cask_${{ matrix.target }}.tar.gz --directory=target/${{ matrix.target }}/release cask

      - name: Build (mac)
        if: startsWith(matrix.os, 'macOS')
        run: |
          rustup target add ${{ matrix.target }}
          cargo build --release --locked --target ${{ matrix.target }}
          tar -cvzf target/${{ matrix.target }}/release/cask_${{ matrix.target }}.tar.gz --directory=target/${{ matrix.target }}/release cask

      - name: Build (windows) - x86_64-pc-windows-msvc
        if: startsWith(matrix.os, 'windows') && startsWith(matrix.target, 'x86_64-pc-windows-msvc')
        run: |
          rustup target add ${{ matrix.target }}

          cargo build --release --locked --target ${{ matrix.target }}

          tar -cvzf target/${{ matrix.target }}/release/cask_${{ matrix.target }}.tar.gz --directory=target/${{ matrix.target }}/release cask.exe

      - name: Build (windows) - aarch64-pc-windows-msvc
        if: startsWith(matrix.os, 'windows') && && startsWith(matrix.target, 'aarch64-pc-windows-msvc')
        run: |
          rustup target add ${{ matrix.target }}

          cargo build --release --locked --target ${{ matrix.target }}

          tar -cvzf target/${{ matrix.target }}/release/cask_${{ matrix.target }}.tar.gz --directory=target/${{ matrix.target }}/release cask.exe

      - name: Release to Github
        uses: softprops/action-gh-release@v1
        if: startsWith(github.repository, 'axetroy') && startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          files: |
            target/x86_64-pc-windows-msvc/release/cask_x86_64-pc-windows-msvc.tar.gz
            target/aarch64-pc-windows-msvc/release/cask_aarch64-pc-windows-msvc.tar.gz

            target/x86_64-unknown-linux-musl/release/cask_x86_64-unknown-linux-musl.tar.gz
            target/aarch64-unknown-linux-musl/release/cask_aarch64-unknown-linux-musl.tar.gz
            target/mips64-unknown-linux-musl/release/cask_mips64-unknown-linux-musl.tar.gz

            target/x86_64-apple-darwin/release/cask_darwin_amd64.tar.gz
            target/aarch64-apple-darwin/release/cask_darwin_arm64.tar.gz
          draft: false
